server:
  servlet:
    context-path: /
#  port: 80

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
    mode: HTML
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.31.130:3306/miaosha?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  redis:
    host: 192.168.31.130
    password: redis
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    # 连接超时时间（毫秒）
    timeout: 0
    jedis:
      pool:
        # 最大连接池数
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 20
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 100
  rabbitmq:
    host: 192.168.31.130
    port: 5672
    username: guest
    password: guest

# 通用mapper
mapper:
  not-empty: true
  identity: MYSQL

mybatis:
  type-aliases-package: com.rjs.miaosha.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  reasonable: true
  support-methods-arguments: true

logging:
  level:
    com.*: debug







